-- Insert 100 demo profiles (50 males looking for females, 50 females looking for males)
INSERT INTO public.profiles (name, age, city, bio, interests, avatar_url, gender, is_online, is_demo, looking_for) VALUES
-- Female profiles (50) - looking for males
('מיכל', 26, 'תל אביב', 'אוהבת לטייל, לקרוא ספרים ולבשל. מחפשת מישהו עם חוש הומור טוב 😊', ARRAY['טיולים', 'בישול', 'יוגה', 'קפה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('נועה', 31, 'חיפה', 'עורכת דין, חובבת אמנות וטבע. מחפשת קשר רציני עם מישהו בעל עומק.', ARRAY['אמנות', 'טבע', 'ריצה', 'תיאטרון'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('שירה', 24, 'רמת גן', 'סטודנטית לפסיכולוגיה עם אהבה גדולה לחתולים 🐱', ARRAY['פסיכולוגיה', 'חתולים', 'נטפליקס'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('תמר', 28, 'באר שבע', 'רופאה בהתמחות, מאמינה שהחיים מתחילים מחוץ לאזור הנוחות 🏔️', ARRAY['רפואה', 'טיפוס', 'יוגה'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('מאיה', 25, 'ראשון לציון', 'מוזיקאית ויוצרת. בעולם שלי יש הרבה נגינה וקפה 🎵', ARRAY['מוזיקה', 'כתיבה', 'הופעות'], '/profiles/profile1.jpg', 'female', false, true, 'male'),
('ליאורה', 27, 'פתח תקווה', 'מתכנתת ומעצבת UX. אוהבת לפתור בעיות 💻', ARRAY['עיצוב', 'טכנולוגיה', 'משחקים'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('אביגיל', 29, 'תל אביב', 'מורה לריקוד וחובבת תרבות 💃', ARRAY['ריקוד', 'מוזיקה', 'תיאטרון'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('יעל', 23, 'הרצליה', 'סטודנטית לתקשורת עם חלומות גדולים ☀️', ARRAY['צילום', 'כתיבה', 'קולנוע'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('רונית', 34, 'ירושלים', 'יועצת ארגונית עם תשוקה לאנשים ☕', ARRAY['פסיכולוגיה', 'קריאה', 'יוגה'], '/profiles/profile1.jpg', 'female', false, true, 'male'),
('הילה', 26, 'נתניה', 'גרפיקאית עם אהבה לאיור 🎨', ARRAY['אמנות', 'עיצוב', 'צילום'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('דנה', 30, 'תל אביב', 'עורכת תוכן ובלוגרית אוכל 🍽️', ARRAY['בישול', 'יין', 'טיולים'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('שקד', 22, 'רעננה', 'סטודנטית למדעי המחשב. גיקית וגאה! 🎮', ARRAY['משחקים', 'טכנולוגיה', 'אנימה'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('ליה', 28, 'חיפה', 'אחות במקצוע, מטפסת הרים בתור תחביב 🧗‍♀️', ARRAY['טיפוס', 'טבע', 'ריצה'], '/profiles/profile1.jpg', 'female', false, true, 'male'),
('עדי', 25, 'אשדוד', 'מעצבת פנים עם עין לפרטים ✨', ARRAY['עיצוב', 'אמנות', 'צילום'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('נטלי', 27, 'תל אביב', 'מורה ליוגה ומדריכת מיינדפולנס 🧘‍♀️', ARRAY['יוגה', 'מדיטציה', 'טבע'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('אורלי', 32, 'ירושלים', 'עורכת דין עם תשוקה לצדק חברתי 💪', ARRAY['משפטים', 'קריאה', 'ריצה'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('שלומית', 29, 'רמת גן', 'שפית קונדיטורית. אתפתה אתכם בעוגות! 🍰', ARRAY['אפייה', 'בישול', 'יין'], '/profiles/profile1.jpg', 'female', false, true, 'male'),
('אלונה', 24, 'הרצליה', 'סטודנטית לביולוגיה ימית 🌊', ARRAY['שחייה', 'צלילה', 'טבע'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('מור', 26, 'תל אביב', 'אנימטורית ומאיירת 🎬', ARRAY['אנימציה', 'ציור', 'קולנוע'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('רומי', 31, 'כפר סבא', 'רואת חשבון ביום, רקדנית סלסה בלילה 💃', ARRAY['ריקוד', 'מוזיקה', 'יין'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('ספיר', 23, 'אילת', 'מדריכת צלילה 🐠', ARRAY['צלילה', 'ים', 'טבע'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('גליה', 28, 'תל אביב', 'יזמת חברתית עם חלום לשנות את העולם 🌍', ARRAY['יזמות', 'וולונטריות', 'טיולים'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('יסמין', 25, 'חיפה', 'מהנדסת תעשייה וניהול 💡', ARRAY['טכנולוגיה', 'עיצוב', 'ריצה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('טלי', 30, 'ראשון לציון', 'פסיכולוגית קלינית ❤️', ARRAY['פסיכולוגיה', 'קריאה', 'יוגה'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('נגה', 27, 'תל אביב', 'צלמת אופנה 📸', ARRAY['צילום', 'אופנה', 'אמנות'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('קרן', 33, 'ירושלים', 'מנהלת פרויקטים בהייטק 📊', ARRAY['טכנולוגיה', 'ריצה', 'יוגה'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('הגר', 26, 'נתניה', 'מורה לאנגלית 📚', ARRAY['שפות', 'קריאה', 'טיולים'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('איילת', 29, 'רעננה', 'וטרינרית עם אהבה לחיות 🐾', ARRAY['חיות', 'טבע', 'הליכות'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('לירון', 24, 'תל אביב', 'דוגמנית וסטודנטית 💫', ARRAY['אופנה', 'יוגה', 'צילום'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('שני', 28, 'באר שבע', 'מהנדסת חשמל 💪', ARRAY['טכנולוגיה', 'ריצה', 'משחקים'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('עינב', 25, 'פתח תקווה', 'מעצבת תכשיטים ✨', ARRAY['אמנות', 'עיצוב', 'אופנה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('דפנה', 31, 'תל אביב', 'עיתונאית חוקרת 🔍', ARRAY['כתיבה', 'קריאה', 'צילום'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('נעמה', 27, 'הרצליה', 'אדריכלית נוף 🌿', ARRAY['טבע', 'עיצוב', 'צילום'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('הדס', 23, 'חיפה', 'סטודנטית לרפואה 🏥', ARRAY['רפואה', 'מדע', 'קריאה'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('שרון', 30, 'ירושלים', 'מנהלת מרכז קהילתי 🤝', ARRAY['וולונטריות', 'אירועים', 'מוזיקה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('יובלה', 26, 'תל אביב', 'קופירייטרית יצירתית ✍️', ARRAY['כתיבה', 'קריאה', 'קולנוע'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('תהילה', 28, 'רמת גן', 'מפיקת אירועים 🎉', ARRAY['אירועים', 'מוזיקה', 'ריקוד'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('מיטל', 32, 'נתניה', 'מנהלת משאבי אנוש 👥', ARRAY['פסיכולוגיה', 'קריאה', 'יוגה'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('שגית', 25, 'אשדוד', 'מורה לכושר ותזונאית 🏋️‍♀️', ARRAY['כושר', 'תזונה', 'ריצה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('לינוי', 29, 'תל אביב', 'מנהלת מותג בחברת אופנה 👗', ARRAY['אופנה', 'עיצוב', 'יין'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('עדנה', 24, 'כפר סבא', 'מורת גן 🧸', ARRAY['ילדים', 'אמנות', 'מוזיקה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('נורית', 33, 'רעננה', 'אדריכלית מצליחה 🏠', ARRAY['אדריכלות', 'עיצוב', 'צילום'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('אורית', 27, 'חיפה', 'מורה ליוגה ופילאטיס 🧘‍♀️', ARRAY['יוגה', 'פילאטיס', 'טבע'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('רננה', 26, 'תל אביב', 'מפתחת אפליקציות 💻', ARRAY['טכנולוגיה', 'משחקים', 'קפה'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('גלית', 30, 'ירושלים', 'סופרת ומשוררת 📖', ARRAY['כתיבה', 'קריאה', 'תיאטרון'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('סיוון', 28, 'הרצליה', 'יועצת עסקית 📈', ARRAY['עסקים', 'קריאה', 'ריצה'], '/profiles/profile3.jpg', 'female', false, true, 'male'),
('אפרת', 25, 'באר שבע', 'סטודנטית למשפטים 📚', ARRAY['משפטים', 'קריאה', 'יוגה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('זהבית', 31, 'תל אביב', 'שפית במסעדת יוקרה 👩‍🍳', ARRAY['בישול', 'יין', 'טיולים'], '/profiles/profile3.jpg', 'female', true, true, 'male'),
('ירדנה', 24, 'נתניה', 'מדריכת כושר ⚡', ARRAY['כושר', 'ריצה', 'שחייה'], '/profiles/profile1.jpg', 'female', true, true, 'male'),
('עמית', 29, 'ראשון לציון', 'מהנדסת ביומדיקל 🔬', ARRAY['מדע', 'טכנולוגיה', 'קריאה'], '/profiles/profile3.jpg', 'female', false, true, 'male'),

-- Male profiles (50) - looking for females
('דניאל', 29, 'ירושלים', 'מהנדס תוכנה ביום, מוזיקאי בלילה 🎸', ARRAY['מוזיקה', 'טכנולוגיה', 'ספורט'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('יונתן', 27, 'הרצליה', 'יזם ומטייל. מאמין שהחיים קצרים ☕', ARRAY['יזמות', 'טיולים', 'צילום'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('עומר', 32, 'תל אביב', 'שף במקצוע, גורמה באופי 🍳', ARRAY['בישול', 'יין', 'טיולים'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('אלון', 30, 'נתניה', 'מאמן כושר וחובב טבע 💪', ARRAY['כושר', 'גלישה', 'טבע'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('רועי', 35, 'רעננה', 'עורך דין בינלאומי 🍷', ARRAY['יין', 'אמנות', 'נסיעות'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('איתי', 33, 'אשדוד', 'ארכיטקט עם תשוקה לעיצוב 🏛️', ARRAY['אדריכלות', 'עיצוב', 'טיולים'], '/profiles/profile4.jpg', 'male', false, true, 'female'),
('אורי', 28, 'תל אביב', 'מנהל מוצר בהייטק 🚀', ARRAY['טכנולוגיה', 'יזמות', 'ריצה'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('נדב', 26, 'חיפה', 'רופא מתמחה עם תשוקה לסייל ⛵', ARRAY['שיט', 'רפואה', 'מוזיקה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('עידו', 31, 'ירושלים', 'היסטוריון ומורה 📚', ARRAY['היסטוריה', 'קריאה', 'תיאטרון'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('שחר', 25, 'רמת גן', 'מפתח משחקים 🎮', ARRAY['משחקים', 'טכנולוגיה', 'אנימה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('גיא', 34, 'תל אביב', 'צלם מקצועי 📷', ARRAY['צילום', 'טיולים', 'אמנות'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('ליאם', 27, 'הרצליה', 'אנליסט פיננסי ביום, סטנדאפיסט בלילה 😄', ARRAY['קומדיה', 'כלכלה', 'ספורט'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('דור', 29, 'נתניה', 'גולש בים וגם בחיים 🏄', ARRAY['גלישה', 'ים', 'טיולים'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('אמיר', 32, 'באר שבע', 'מהנדס אזרחי שבונה חלומות 🏗️', ARRAY['הנדסה', 'טיולים', 'בישול'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('נועם', 24, 'תל אביב', 'סטודנט לקולנוע 🎬', ARRAY['קולנוע', 'צילום', 'כתיבה'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('תום', 30, 'ראשון לציון', 'מנהל שיווק דיגיטלי 📱', ARRAY['שיווק', 'טכנולוגיה', 'כושר'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('רון', 28, 'כפר סבא', 'מטפל פיזיותרפיה ❤️‍🩹', ARRAY['בריאות', 'כושר', 'יוגה'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('ניר', 33, 'חיפה', 'קברניט בחברת תעופה ✈️', ARRAY['טיסות', 'טיולים', 'צילום'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('יואב', 26, 'ירושלים', 'מוזיקאי וזמר 🎵', ARRAY['מוזיקה', 'כתיבה', 'הופעות'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('אייל', 31, 'תל אביב', 'יועץ ניהול 📊', ARRAY['עסקים', 'קריאה', 'ריצה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('בן', 29, 'רעננה', 'רופא שיניים עם חיוך יפה 😁', ARRAY['רפואה', 'כושר', 'בישול'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('יובל', 25, 'פתח תקווה', 'מעצב גרפי יצירתי 🎨', ARRAY['עיצוב', 'אמנות', 'צילום'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('מתן', 34, 'תל אביב', 'יזם טכנולוגי 💡', ARRAY['יזמות', 'טכנולוגיה', 'כושר'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('עמרי', 27, 'אשדוד', 'מהנדס אלקטרוניקה ⚡', ARRAY['טכנולוגיה', 'משחקים', 'ספורט'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('לביא', 30, 'הרצליה', 'עורך וידאו ויוצר תוכן 🎥', ARRAY['קולנוע', 'צילום', 'טיולים'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('ארז', 32, 'תל אביב', 'סוכן נדלן מצליח 🏡', ARRAY['נדלן', 'השקעות', 'יין'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('אסף', 28, 'נתניה', 'טריינר אישי 🏋️', ARRAY['כושר', 'תזונה', 'ריצה'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('גיל', 26, 'חיפה', 'מפתח תוכנה וחובב טבע 🌲', ARRAY['טכנולוגיה', 'טבע', 'הליכות'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('אילן', 35, 'ירושלים', 'פרופסור לכלכלה 📈', ARRAY['כלכלה', 'קריאה', 'יין'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('ינון', 29, 'רמת גן', 'מאמן כדורסל לנוער 🏀', ARRAY['כדורסל', 'ספורט', 'חינוך'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('עידן', 27, 'תל אביב', 'DJ ומפיק מוזיקה 🎧', ARRAY['מוזיקה', 'הופעות', 'מסיבות'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('אריאל', 31, 'באר שבע', 'מנהל פרויקטים 🎯', ARRAY['טכנולוגיה', 'ספורט', 'קריאה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('שי', 24, 'כפר סבא', 'סטודנט למשפטים ⚖️', ARRAY['משפטים', 'קריאה', 'ריצה'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('אסי', 33, 'תל אביב', 'שף סושי 🍣', ARRAY['בישול', 'יפן', 'יין'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('יניב', 28, 'הרצליה', 'יועץ פיננסי 💰', ARRAY['כלכלה', 'השקעות', 'ספורט'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('נתי', 30, 'ראשון לציון', 'מהנדס רובוטיקה 🤖', ARRAY['רובוטיקה', 'טכנולוגיה', 'משחקים'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('גלעד', 26, 'אילת', 'מדריך צלילה 🐬', ARRAY['צלילה', 'ים', 'גלישה'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('אמיתי', 32, 'תל אביב', 'במאי תיאטרון 🎭', ARRAY['תיאטרון', 'קולנוע', 'כתיבה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('הדר', 27, 'חיפה', 'אגרונום וחקלאי 🌱', ARRAY['חקלאות', 'טבע', 'בישול'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('מיכאל', 29, 'ירושלים', 'רב ומחנך 🙏', ARRAY['רוחניות', 'חינוך', 'קהילה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('דביר', 25, 'נתניה', 'מעצב תעשייתי 🔧', ARRAY['עיצוב', 'טכנולוגיה', 'אמנות'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('יהונתן', 34, 'תל אביב', 'מנתח מערכות בכיר 💻', ARRAY['טכנולוגיה', 'קריאה', 'שחמט'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('נריה', 28, 'רעננה', 'מאמן כושר לילדים 👦', ARRAY['ספורט', 'חינוך', 'כושר'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('יותם', 30, 'פתח תקווה', 'מנהל רשתות חברתיות 📲', ARRAY['שיווק', 'צילום', 'טיולים'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('רפאל', 33, 'אשדוד', 'מהנדס ימי ⚓', ARRAY['ים', 'הנדסה', 'שיט'], '/profiles/profile2.jpg', 'male', false, true, 'female'),
('טל', 26, 'תל אביב', 'שחקן תיאטרון 🎪', ARRAY['תיאטרון', 'קולנוע', 'ריקוד'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('דרור', 31, 'חיפה', 'טייס מסוקים 🚁', ARRAY['טיסה', 'הרפתקאות', 'צילום'], '/profiles/profile2.jpg', 'male', true, true, 'female'),
('שלומי', 29, 'ירושלים', 'מורה לפיזיקה ⚛️', ARRAY['מדע', 'הוראה', 'קריאה'], '/profiles/profile4.jpg', 'male', true, true, 'female'),
('ברק', 32, 'תל אביב', 'מנהל R&D בסטארטאפ ⚡', ARRAY['טכנולוגיה', 'יזמות', 'ספורט'], '/profiles/profile2.jpg', 'male', true, true, 'female');